########################################################
#@@@-------------GENERATED BY AUTO_MAKE-------------@@@#
#@@                                                  @@#
#@    https://github.com/kagestonedragon/auto_make    @#
########################################################

NAME = push_swap_ex

GCC = gcc

GCC_FLAGS = -Wall -Wextra -Werror

OBJ_PATH = objects/

INCLUDES_INCLUDE = includes/

PUSH_SWAP_PATH = push_swap/
PUSH_SWAP_ALGORITHM_PATH = push_swap/algorithm/
PUSH_SWAP_ERRORS_PATH = push_swap/errors/
PUSH_SWAP_INITIALIZATION_PATH = push_swap/initialization/
PUSH_SWAP_OPERATIONS_PATH = push_swap/operations/
PUSH_SWAP_VALIDATION_PATH = push_swap/validation/

PUSH_SWAP_FILES = \
		main.c 
PUSH_SWAP_ALGORITHM_FILES = \
		add_operation.c \
		algorithm.c \
		mediana_search.c \
		primitive_sorting.c \
		print_operations.c \
		optimization.c
PUSH_SWAP_ERRORS_FILES = \
		push_swap_log.c 
PUSH_SWAP_INITIALIZATION_FILES = \
		initialization.c \
		new_list.c 
PUSH_SWAP_OPERATIONS_FILES = \
		push.c \
		reverse_rotate.c \
		rotate.c \
		swap.c 
PUSH_SWAP_VALIDATION_FILES = \
		validation.c 

OBJ_PUSH_SWAP_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_FILES:.c=.o))
OBJ_PUSH_SWAP_ALGORITHM_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_ALGORITHM_FILES:.c=.o))
OBJ_PUSH_SWAP_ERRORS_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_ERRORS_FILES:.c=.o))
OBJ_PUSH_SWAP_INITIALIZATION_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_INITIALIZATION_FILES:.c=.o))
OBJ_PUSH_SWAP_OPERATIONS_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_OPERATIONS_FILES:.c=.o))
OBJ_PUSH_SWAP_VALIDATION_CORE = $(addprefix $(OBJ_PATH), $(PUSH_SWAP_VALIDATION_FILES:.c=.o))

OBJECTS = $(OBJ_PUSH_SWAP_CORE) $(OBJ_PUSH_SWAP_ALGORITHM_CORE) $(OBJ_PUSH_SWAP_ERRORS_CORE) $(OBJ_PUSH_SWAP_INITIALIZATION_CORE) $(OBJ_PUSH_SWAP_OPERATIONS_CORE) $(OBJ_PUSH_SWAP_VALIDATION_CORE) 

all: $(NAME)

$(NAME): $(OBJECTS)
		@($(GCC) $(GCC_FLAGS) $(OBJECTS) -o $(NAME) -L libraries -lft)
		@(echo "[0;92m"$(NAME) "was created![0;0m")

clean:
		@(/bin/rm -rf $(OBJ_PATH))
		@(echo "[0;91mAll object files have been deleted![0;0m")

fclean: clean
		@(/bin/rm -f $(NAME))
		@(echo "[0;91m"$(NAME) "has been deleted![0;0m")

re: fclean all

objects:
		@(mkdir $(OBJ_PATH))

objects/%.o: $(PUSH_SWAP_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(PUSH_SWAP_ALGORITHM_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(PUSH_SWAP_ERRORS_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(PUSH_SWAP_INITIALIZATION_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(PUSH_SWAP_OPERATIONS_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")

objects/%.o: $(PUSH_SWAP_VALIDATION_PATH)%.c | objects
		@($(GCC) $(GCC_FLAGS) -I $(INCLUDES_INCLUDE) -c $< -o $@)
		@(echo "[0;93m"$< "->" $@"[0;0m")
